# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 910bd31e10efb7f7e73736d375b7977714abafd52bd9f5129324baaf7f31afc4a9b266be5b524f72f2eb10a1b3e55d445475d2f0bbb5ff84895fa5642734c87d

test:
  secret_key_base: 9ea90a73ca1aad275edd8861102a89bcd69ca31f1512dbf494f512f30d7f429a1e07841936c110b56ac13a900d6a6c8b48aefd26745ee60c14009b4b404d0be8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
